services:
  palette:
    image: ghcr.io/ergrassa/palette:latest
    container_name: palette
    environment:
      - VIRTUAL_HOST=palette.zerog.cc
      - LETSENCRYPT_HOST=palette.zerog.cc
      - LETSENCRYPT_EMAIL=uzuri@zerog.cc
      - VIRTUAL_PORT=80
    networks:
      - proxy

networks:
  proxy:
    external: true